/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#1a1c1c",
        "primary-fixed": "#e2e2e2",
        "inverse-surface": "#2f3131",
        "on-primary-fixed-variant": "#454747",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#f9f9f9",
        "surface-container-highest": "#e2e2e2",
        "on-secondary-fixed-variant": "#574500",
        "on-secondary-container": "#745c00",
        "outline-variant": "#c4c7c8",
        "tertiary-fixed": "#e5e2e1",
        "background": "#f9f9f9",
        "tertiary-fixed-dim": "#c8c6c5",
        "on-tertiary-fixed-variant": "#474746",
        "error": "#ba1a1a",
        "tertiary": "#5f5e5e",
        "surface-variant": "#e2e2e2",
        "on-error-container": "#93000a",
        "surface": "#f9f9f9",
        "tertiary-container": "#ffffff",
        "on-tertiary": "#ffffff",
        "secondary": "#735c00",
        "brand-gold": "#D4AF37",
        "on-primary": "#ffffff",
        "surface-container": "#eeeeee",
        "on-surface-variant": "#444748",
        "on-secondary-fixed": "#241a00",
        "inverse-primary": "#c6c6c7",
        "on-primary-container": "#747676",
        "primary": "#5d5f5f",
        "secondary-fixed": "#ffe088",
        "on-background": "#1a1c1c",
        "primary-fixed-dim": "#c6c6c7",
        "secondary-container": "#fed65b",
        "on-secondary": "#ffffff",
        "surface-dim": "#dadada",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#1c1b1b",
        "on-tertiary-container": "#777575",
        "surface-container-low": "#f3f3f3",
        "surface-tint": "#5d5f5f",
        "surface-container-high": "#e8e8e8",
        "on-surface": "#1a1c1c",
        "outline": "#747878",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#e9c349",
        "inverse-on-surface": "#f0f1f1",
        "primary-container": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "section-gap": "120px",
        "container-max": "1280px",
        "unit": "8px",
        "margin-mobile": "24px",
        "margin-desktop": "80px",
        "gutter": "32px"
      },
      fontFamily: {
        "label-md": ["Inter"],
        "body-md": ["Inter"],
        "label-sm": ["Inter"],
        "headline-sm": ["Playfair Display"],
        "display-lg": ["Playfair Display"],
        "headline-lg": ["Playfair Display"],
        "headline-lg-mobile": ["Playfair Display"],
        "headline-md": ["Playfair Display"],
        "body-lg": ["Inter"]
      },
      fontSize: {
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.1em", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "26px", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.15em", "fontWeight": "600" }],
        "headline-sm": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "display-lg": ["64px", { "lineHeight": "72px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "headline-lg-mobile": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
        "headline-md": ["32px", { "lineHeight": "40px", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "30px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
